services:
  registry:
    image: ghcr.io/zwqgkd/two-pass-registry-service:latest
    networks:
      - app-network
    ports:
      - "50022:8180"

  provider1:
    image: ghcr.io/zwqgkd/two-pass-time-service:latest
    ports:
      - "50121:8280"
    environment:
      - MY_REGISTER_DISCOVERY_SERVER-ADDR=registry:8180
    networks:
      - app-network
    depends_on:
      - registry

  provider2:
    image: ghcr.io/zwqgkd/two-pass-time-service:latest
    ports:
      - "50222:8280"
    environment:
      - MY_REGISTER_DISCOVERY_SERVER-ADDR=registry:8180
    networks:
      - app-network
    depends_on:
      - registry

  consumer1:
    image: ghcr.io/zwqgkd/two-pass-client:latest
    ports:
      - "50371:8300"
    environment:
      - MY_REGISTER_DISCOVERY_SERVER-ADDR=registry:8180
    networks:
      - app-network
    depends_on:
      - registry

  consumer2:
    image: ghcr.io/zwqgkd/two-pass-client:latest
    ports:
      - "50472:8300"
    environment:
      - MY_REGISTER_DISCOVERY_SERVER-ADDR=registry:8180
    networks:
      - app-network
    depends_on:
      - registry
networks:
  app-network:
